# Generated by Django 4.2.7 on 2024-05-09 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_code', models.CharField(max_length=100)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dcls_month', models.CharField(max_length=20)),
                ('join_way', models.CharField(max_length=100)),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('join_deny', models.IntegerField(blank=True, null=True)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('contract_user', models.ManyToManyField(related_name='contract_saving', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type_nm', models.CharField(max_length=2)),
                ('rsrv_type_nm', models.CharField(max_length=10)),
                ('save_trm', models.CharField(max_length=3)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('saving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.savingproducts')),
            ],
        ),
        migrations.CreateModel(
            name='DepositProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_code', models.CharField(max_length=100, unique=True)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('dcls_month', models.CharField(max_length=20)),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('join_deny', models.IntegerField(blank=True, null=True)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('join_way', models.CharField(max_length=100)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('contract_user', models.ManyToManyField(related_name='contract_deposit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_code', models.TextField()),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('save_trm', models.CharField(max_length=3)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.depositproducts')),
            ],
        ),
        migrations.CreateModel(
            name='CreditLoanProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditloan_code', models.CharField(max_length=100)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dcls_month', models.CharField(max_length=20)),
                ('join_way', models.CharField(max_length=100)),
                ('crdt_prdt_type', models.CharField(max_length=100)),
                ('cb_name', models.TextField()),
                ('dcls_strt_day', models.CharField(max_length=100)),
                ('dcls_end_day', models.CharField(max_length=100)),
                ('fin_co_subm_day', models.CharField(max_length=100)),
                ('contract_user', models.ManyToManyField(related_name='contract_credit_loan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditLoanOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crdt_lend_rate_type', models.CharField(max_length=100)),
                ('crdt_lend_rate_type_nm', models.CharField(max_length=2)),
                ('crdt_grad_1', models.FloatField(null=True)),
                ('crdt_grad_4', models.FloatField(null=True)),
                ('crdt_grad_5', models.FloatField(null=True)),
                ('crdt_grad_6', models.FloatField(null=True)),
                ('crdt_grad_10', models.FloatField(null=True)),
                ('crdt_grad_11', models.FloatField(null=True)),
                ('crdt_grad_12', models.FloatField(null=True)),
                ('crdt_grad_13', models.FloatField(null=True)),
                ('crdt_grad_avg', models.FloatField(null=True)),
                ('creditloan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.creditloanproducts')),
            ],
        ),
    ]
