# Generated by Django 4.2.7 on 2024-05-22 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLoanProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditloan_code', models.CharField(max_length=100, unique=True)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('dcls_month', models.CharField(max_length=20)),
                ('crdt_prdt_type_nm', models.CharField(max_length=100)),
                ('join_way', models.CharField(blank=True, max_length=100, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('rpay_type_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('cb_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_code', models.CharField(max_length=100, unique=True)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('dcls_month', models.CharField(max_length=20)),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('join_deny', models.IntegerField(blank=True, null=True)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('join_way', models.CharField(max_length=100)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('dcls_strt_day', models.CharField(blank=True, max_length=20, null=True)),
                ('dcls_end_day', models.CharField(blank=True, max_length=20, null=True)),
                ('fin_co_subm_day', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_code', models.CharField(max_length=100, unique=True)),
                ('fin_co_no', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('dcls_month', models.CharField(max_length=20)),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('join_deny', models.IntegerField(blank=True, null=True)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('join_way', models.CharField(max_length=100)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('saving_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.savingproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='savingproducts',
            name='contract_user',
            field=models.ManyToManyField(blank=True, related_name='contract_saving', through='instruments.SavingSubscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SavingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_code', models.CharField(default='', max_length=100)),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('save_trm', models.CharField(max_length=3)),
                ('saving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.savingproducts')),
            ],
        ),
        migrations.CreateModel(
            name='DepositSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('deposit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.depositproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='contract_user',
            field=models.ManyToManyField(blank=True, related_name='contract_deposit', through='instruments.DepositSubscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DepositOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_code', models.CharField(max_length=100)),
                ('intr_rate_type', models.CharField(max_length=100)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('save_trm', models.CharField(max_length=3)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.depositproducts')),
            ],
        ),
        migrations.CreateModel(
            name='CreditLoanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('creditloan_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.creditloanproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='creditloanproducts',
            name='contract_user',
            field=models.ManyToManyField(blank=True, related_name='contract_creditloan', through='instruments.CreditLoanSubscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CreditLoanOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditloan_code', models.CharField(max_length=100)),
                ('crdt_lend_rate_type', models.CharField(default='A', max_length=1)),
                ('crdt_lend_rate_type_nm', models.CharField(default='기본금리', max_length=100)),
                ('crdt_grad_1', models.FloatField(null=True)),
                ('crdt_grad_4', models.FloatField(null=True)),
                ('crdt_grad_5', models.FloatField(null=True)),
                ('crdt_grad_6', models.FloatField(null=True)),
                ('crdt_grad_10', models.FloatField(null=True)),
                ('crdt_grad_11', models.FloatField(null=True)),
                ('crdt_grad_12', models.FloatField(null=True)),
                ('crdt_grad_13', models.FloatField(null=True)),
                ('crdt_grad_avg', models.FloatField(null=True)),
                ('creditloan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.creditloanproducts')),
            ],
        ),
    ]
