# Generated by Django 4.2.7 on 2024-05-20 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditloanproducts',
            name='contract_user',
            field=models.ManyToManyField(blank=True, related_name='contract_credit_loan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='contract_user',
            field=models.ManyToManyField(blank=True, related_name='contract_deposit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='contract_user',
            field=models.ManyToManyField(blank=True, related_name='contract_saving', to=settings.AUTH_USER_MODEL),
        ),
    ]
