# Generated by Django 4.2.7 on 2024-05-20 01:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instruments', '0002_alter_creditloanproducts_contract_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditloanoptions',
            old_name='crdt_lend_rate_type',
            new_name='creditloan_code',
        ),
        migrations.RenameField(
            model_name='creditloanproducts',
            old_name='dcls_end_day',
            new_name='fin_prdt_nm',
        ),
        migrations.RenameField(
            model_name='creditloanproducts',
            old_name='dcls_strt_day',
            new_name='rpay_type_nm',
        ),
        migrations.RenameField(
            model_name='savingproducts',
            old_name='name',
            new_name='fin_prdt_nm',
        ),
        migrations.RemoveField(
            model_name='creditloanoptions',
            name='crdt_grad_10',
        ),
        migrations.RemoveField(
            model_name='creditloanoptions',
            name='crdt_grad_11',
        ),
        migrations.RemoveField(
            model_name='creditloanoptions',
            name='crdt_grad_12',
        ),
        migrations.RemoveField(
            model_name='creditloanoptions',
            name='crdt_grad_13',
        ),
        migrations.RemoveField(
            model_name='creditloanoptions',
            name='crdt_grad_avg',
        ),
        migrations.RemoveField(
            model_name='creditloanoptions',
            name='crdt_lend_rate_type_nm',
        ),
        migrations.RemoveField(
            model_name='creditloanproducts',
            name='fin_co_subm_day',
        ),
        migrations.RemoveField(
            model_name='creditloanproducts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='savingoptions',
            name='rsrv_type_nm',
        ),
        migrations.AddField(
            model_name='creditloanproducts',
            name='max_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditloanproducts',
            name='spcl_cnd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingoptions',
            name='saving_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='creditloanproducts',
            name='cb_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='creditloanproducts',
            name='contract_user',
            field=models.ManyToManyField(blank=True, related_name='contract_creditloan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditloanproducts',
            name='creditloan_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='depositoptions',
            name='deposit_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='intr_rate_type_nm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='savingproducts',
            name='saving_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
