# Generated by Django 4.2.7 on 2024-05-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_rename_crdt_lend_rate_type_creditloanoptions_creditloan_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditloanoptions',
            name='crdt_grad_10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='creditloanoptions',
            name='crdt_grad_11',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='creditloanoptions',
            name='crdt_grad_12',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='creditloanoptions',
            name='crdt_grad_13',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='creditloanoptions',
            name='crdt_grad_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='creditloanoptions',
            name='crdt_lend_rate_type',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='creditloanoptions',
            name='crdt_lend_rate_type_nm',
            field=models.CharField(default='기본금리', max_length=100),
        ),
        migrations.AlterField(
            model_name='creditloanproducts',
            name='cb_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creditloanproducts',
            name='join_way',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creditloanproducts',
            name='rpay_type_nm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
