# Generated by Django 4.2.7 on 2024-05-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_creditloanoptions_crdt_grad_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='dcls_strt_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='fin_co_subm_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
