# Generated by Django 4.2.7 on 2024-05-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_depositproducts_dcls_end_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditloanproducts',
            old_name='crdt_prdt_type',
            new_name='crdt_prdt_type_nm',
        ),
    ]
