# Generated by Django 4.2.7 on 2024-05-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_rename_crdt_prdt_type_creditloanproducts_crdt_prdt_type_nm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositoptions',
            old_name='intr_rate_type_nm',
            new_name='intr_rate_type',
        ),
    ]
