# Generated by Django 4.2.7 on 2024-05-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user_age_group', models.CharField(choices=[('10s', '10대'), ('20s', '20대'), ('30s', '30대')], max_length=3)),
                ('service_purpose', models.CharField(choices=[('A', '서비스 목적 A'), ('B', '서비스 목적 B')], max_length=1)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('asset', models.BigIntegerField(default=0)),
                ('auth_number', models.IntegerField(default=0)),
                ('user_status', models.BooleanField(default=True)),
            ],
        ),
    ]
