# Generated by Django 4.2.7 on 2024-05-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('user_age_group', models.CharField(choices=[('10s', '10대'), ('20s', '20대'), ('30s', '30대'), ('40s', '40대'), ('50s', '50대')], max_length=3)),
                ('service_purpose', models.CharField(choices=[('A', '서비스 목적 A'), ('B', '서비스 목적 B'), ('C', '서비스 목적 C')], max_length=1)),
                ('asset', models.BigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
