# Generated by Django 4.2.7 on 2024-05-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_number',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='service_purpose',
            field=models.CharField(choices=[('A', '서비스 목적 A'), ('B', '서비스 목적 B'), ('C', '서비스 목적 C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_age_group',
            field=models.CharField(choices=[('10s', '10대'), ('20s', '20대'), ('30s', '30대'), ('40s', '40대'), ('50s', '50대')], max_length=3),
        ),
    ]
