# Generated by Django 4.2.7 on 2024-05-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service_purpose',
            field=models.CharField(choices=[('예금 가입', '예금 가입'), ('적금 가입', '적금 가입'), ('대출 가입', '대출 가입')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_age_group',
            field=models.CharField(choices=[('10대', '10대'), ('20대', '20대'), ('30대', '30대'), ('40대', '40대'), ('50대', '50대')], max_length=3),
        ),
    ]
