# Generated by Django 4.2.7 on 2024-05-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_account_number_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_age_group',
            field=models.CharField(choices=[('10s', '10대'), ('20s', '20대'), ('30s', '30대'), ('40s', '30대'), ('50s', '30대')], max_length=3),
        ),
    ]
