# Generated by Django 4.2.7 on 2024-05-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_age_group',
            field=models.CharField(choices=[('10s', '10대'), ('20s', '20대'), ('30s', '30대'), ('40s', '40대'), ('50s', '50대')], max_length=3),
        ),
    ]
